### ISSUE TITLE
Compiler supports: MOOSE builds or does not build with following compilers

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#98]
MOOSE compiles with most of the recent `gcc` and `clang` compilers. It has been tested with `gcc4.7+` and `clang3.x` compilers. On CentOS-6 and CentOS-5, the default compilers are `gcc-4.4` and `gcc-4.1`. On CentOS-5, one can install `gcc-4.4` from epel repositories. Efforts have been made to make sure that MOOSE compiles with `gcc-4.4`. This ticket keeps track of it.

This table summaries the status of MOOSE build with compilers.

Compiler | Version/OS | Build? | Comment |
------------|-----------|----------|-------------|
gcc         |  4.1/CentOS-5    |   Yes    |  `libsbml-5.9.0` can't be linked. You have to disable the SBML support. Various link time errors with libstd. Too many compile time warnings. __This compiler is not supported__. |
gcc         | 4.4/CentOS-5      |   Yes, All unit test passes , All py-moose tests also passes      |                |

Unfortunately, `gcc-4.4` does not support may `c++11` features. Thereby no `c++11` construct is used in `master` branch. When `moose` is compiled with `WITH_BOOST`, it may use `c++11` constructs provided by `boost` libraries.

**Comment by dilawar** [comment]
gcc-4.1 compiles the MOOSE but `libsbml` doesn't link (even though it is compiled with same compiler).

~~~~
/usr/local/lib/libsbml.so: undefined reference to `long std::__copy_streambufs_eof<char, std::char_traits<char> >(std::basic_streambuf<char, std::char_traits<char> >*, std::basic_streambuf<char, std::char_traits<char> >*, bool&)@GLIBCXX_3.4.9'
collect2: ld returned 1 exit status
~~~~
