### PR TITLE
Test xreacs

### PR DESCRIPTION
**Pull request by dilawar**
Adds a test-suite by Upi to cmake test flow. One of these tests are failing with merges after #280 

- [x] testXchan1.py

### CODE REVIEW

**Comment by dilawar** [comment]
@BhallaLab/mooser tests are failing because, `kkit` requires solver to be setup by calling `moose.mooseAddChemSolver( 'model', 'solver')`. I've added this line to the test but it function is failing.

```
No CPU information available. Assuming single core.
No CPU information available. Assuming single core.
on node 0, numNodes = 1, numCores = 1
[INFO ] Using moose from /home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/__init__.py, 3.2.0-2153ed0e4
KSolver is deleted for modelpath <moose.vec: class=Ksolve, id=468, path=/model[0]/compartment[0]/ksolve> 
DSolver is deleted for modelpath <moose.vec: class=Dsolve, id=469, path=/model[0]/dsolve> 
KSolver is deleted for modelpath <moose.vec: class=Ksolve, id=470, path=/model[0]/endo[0]/ksolve> 
DSolver is deleted for modelpath <moose.vec: class=Dsolve, id=471, path=/model[0]/endo[0]/dsolve> 
Traceback (most recent call last):
  File "../tests/python/testXchan1.py", line 183, in <module>
    main( standalone = True )
  File "../tests/python/testXchan1.py", line 141, in main
    moose.mooseAddChemSolver( 'model', 'gsl' )
  File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/moose.py", line 210, in mooseAddChemSolver
    chemError_ = _chemUtil.add_Delete_ChemicalSolver.mooseAddChemSolver(modelpath, solver)
  File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/chemUtil/add_Delete_ChemicalSolver.py", line 62, in mooseAddChemSolver
    setCompartmentSolver(modelRoot, currentSolver)
  File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/chemUtil/add_Delete_ChemicalSolver.py", line 78, in setCompartmentSolver
    positionCompt(compts)
  File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/chemUtil/add_Delete_ChemicalSolver.py", line 9, in positionCompt
    compt[i+1].x1 += compt[i].x1
AttributeError: 'moose.EndoMesh' object has no attribute 'x1'
```

Probably a regression caused by #277 . Though I am not sure.

**Comment by dilawar** [comment]
Test fails because of #280

**Comment by upibhalla** [comment]
I have mailed in a corrected testXchan1.py. See if that works.
-- Upi

**Comment by dilawar** [comment]
Passes locally. Once it is cleared by travis, it can be merged into master.
